# Check out https://docs.codemagic.io/getting-started/yaml/ for more information

workflows:
    flutter-widget:
        name: My workflow name
        instance_type: mac_mini
        max_build_duration: 120
        type: "SLEEP"
        trigger_time: "ON_EVERY_EXECUTION"
        sleep_in_sec: 7200
